<?php

// Requête SQL pour récupérer tous les utilisateurs dans la base de donnée
$query = $db->prepare("SELECT * FROM users ORDER BY email ASC");
$query->execute();
$users = $query->fetchAll(PDO::FETCH_ASSOC);

?>

<main class="container py-5">
    <h1>
        Liste des utilisateurs
    </h1>
    <a href="" class="btn btn-primary mt-3"><span class="bi-plus-circle-fill"></span> Créer un utilisateur</a>
    <table class="my-5 table table-striped">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Prénom
                </th>
                <th>
                    Nom
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) { ?>
            <tr>
                <td><?= $user["id"]; ?></td>
                <td><?= $user["email"]; ?></td>
                <td><?= $user["password"]; ?></td>
                <td><?= $user["first_name"]; ?></td>
                <td><?= $user["last_name"]; ?></td>
                <td>
                    <a href="index.php?route=show-user&id=<?= $user["id"]; ?>" class="btn btn-primary"><scan class="bi-eye-fill"></scan></a>
                    <a href="index.php?route=edit-user&id=<?= $user["id"]; ?>" class="btn btn-success"><scan class="bi-pencil-fill"></scan></a>
                    <a href="logic/delete-user.php?id=<?= $user["id"]; ?>" class="btn btn-danger"><scan class="bi-trash-fill"></scan></a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
        <tfoot>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Prénom
                </th>
                <th>
                    Nom
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </tfoot>
    </table>
    
    <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
       <p>Utilisateur supprimé avec succès</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</main>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    // Récupérer la variable GET 'delete_success'
    const deleteSuccess = "<?php echo isset($_GET['delete_success']) ? $_GET['delete_success'] : ''; ?>";

    // Si la suppression a réussi, afficher la modal
    if (deleteSuccess === 'true') {
        $(document).ready(function () {
            $('#exampleModal').modal('show');
        });
    }
</script>